# whitelist
branches:
  only:
    - galileo
    - master

before_script:
  - "scons -c"
  - "sudo apt-get install libsdl2-dev"
  - "sudo apt-get install libsdl2-image-dev"
  - "git submodule init"
  - "git submodule update"
  - "cd src/thirdparty/v8 && make dependencies && make native.release component=shared_library -j8 i18nsupport=off && sudo cp out/native.release/libv8.so /usr/local/lib/libv8.so && cd ../../.."
script: "scons"
install: true

